# .github/workflows/build.yml

name: Build MOT-CycleControl Firmware

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ==========================================================
      # == TAMBAHKAN LANGKAH BARU INI ==
      # Ini memaksa git untuk mengganti https -> http
      # untuk mengatasi bug 'could not read Username' di CI
      - name: Disable Git HTTPS redirection for GitHub
        run: git config --global url."http://github.com/".insteadOf "https://github.com/"
      # ==========================================================

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build PlatformIO Project
        run: pio run -e esp32dev

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          path: .pio/build/esp32dev/firmware.bin
          
