# .github/workflows/build.yml

name: Build MOT-CycleControl Firmware

# Kapan workflow ini berjalan:
on:
  # 1. Setiap kali ada push ke branch 'main' atau 'master'
    push:
        branches: [ "main", "master" ]

            # 2. Setiap kali ada Pull Request yang ditargetkan ke 'main' atau 'master'
              pull_request:
                  branches: [ "main", "master" ]

                        # 3. Memungkinkan Anda menjalankan workflow ini secara manual dari tab Actions
                          workflow_dispatch:

                          jobs:
                            build:
                                # Menggunakan OS Ubuntu terbaru untuk build
                                    runs-on: ubuntu-latest

                                        steps:
                                              # Langkah 1: Checkout (mengunduh) kode Anda dari repository
                                                    - name: Checkout repository
                                                            uses: actions/checkout@v4

                                                                  # Langkah 2: Setup lingkungan Python (diperlukan oleh PlatformIO)
                                                                        - name: Set up Python 3.11
                                                                                uses: actions/setup-python@v5
                                                                                        with:
                                                                                                  python-version: '3.11'

                                                                                                        # Langkah 3: Install PlatformIO Core
                                                                                                              - name: Install PlatformIO
                                                                                                                      run: |
                                                                                                                                python -m pip install --upgrade pip
                                                                                                                                          pip install platformio
                                                                                                                                          
                                                                                                                                                # Langkah 4: Menjalankan build (sesuai spesifikasi 8)
                                                                                                                                                      # Ini akan meng-compile kode dan library
                                                                                                                                                            - name: Build PlatformIO Project
                                                                                                                                                                    run: pio run -e esp32dev
                                                                                                                                                                    
                                                                                                                                                                          # Langkah 5: Mengunggah hasil build (file .bin) sebagai Artifact
                                                                                                                                                                                # Ini memungkinkan Anda mengunduh file firmware.bin yang sudah jadi
                                                                                                                                                                                      - name: Upload Firmware Artifact
                                                                                                                                                                                              uses: actions/upload-artifact@v4
                                                                                                                                                                                                      with:
                                                                                                                                                                                                                name: firmware-bin
                                                                                                                                                                                                                          path: .pio/build/esp32dev/firmware.bin
