name: Build ESP32 Firmware

# Memicu workflow ini setiap kali ada 'push' atau 'pull request'
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest # Menggunakan server Linux

    steps:
    - name: Checkout repository
      # Mengunduh kode Anda dari repo ke server
      uses: actions/checkout@v4

    - name: Set up Python
      # PlatformIO membutuhkan Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install PlatformIO Core
      # Menginstal PlatformIO di server
      run: pip install -U platformio

    - name: Run PlatformIO Build
      # Menjalankan perintah build
      run: pio run

    - name: Upload Firmware Artifact
      # Ini adalah bagian yang Anda inginkan:
      # Mengambil file firmware.bin yang sudah jadi dan menyimpannya
      # agar bisa Anda download.
      uses: actions/upload-artifact@v4
      with:
        name: esp32-firmware
        # Lokasi file .bin hasil build
        path: .pio/build/esp32dev/firmware.bin
